package com.ayuvo.health.models

/**
 * Health Data hub metric registry — the Android mirror of `shared/health/metric_registry.json`
 * (parity-tested by HealthDataTypeContractTest; the entry block below is generated from that
 * file and must be regenerated, never hand-edited, when the contract changes). Pure Kotlin:
 * nothing here may import androidx or Compose so the sync engine and its JVM tests stay
 * framework-free.
 *
 * Conventions shared with iOS: percent stored 0–100, durations in seconds, SI-ish units,
 * unknown native types stored under their raw id in category `other`.
 */
enum class HealthCategory(val id: String) {
    ACTIVITY("activity"),
    BODY("body"),
    CYCLE_TRACKING("cycle_tracking"),
    HEARING("hearing"),
    HEART("heart"),
    MENTAL_WELLBEING("mental_wellbeing"),
    MOBILITY("mobility"),
    NUTRITION("nutrition"),
    RESPIRATORY("respiratory"),
    SLEEP("sleep"),
    SYMPTOMS("symptoms"),
    VITALS("vitals"),
    OTHER("other");

    companion object {
        fun byId(id: String): HealthCategory? = entries.firstOrNull { it.id == id }
    }
}

enum class HealthKind(val id: String) {
    CUMULATIVE("cumulative"), DISCRETE("discrete"), DURATION("duration"),
    CATEGORY("category"), SESSION("session"), SERIES("series");

    companion object {
        fun byId(id: String): HealthKind? = entries.firstOrNull { it.id == id }
    }
}

enum class HealthAggregation { SUM, DURATION, AVERAGE, MIN_MAX, LATEST, COUNT }

enum class HealthDayAttribution(val id: String) {
    START("start"), END("end"), SPAN("span")
}

enum class HealthAndroidTier { CORE, EXTENDED }

/**
 * Platform feature gates; mapped to `HealthConnectFeatures` constants only inside the manager.
 * [registryName] is the constant name the shared registry uses for `hc_feature_flag`.
 */
enum class HealthFeatureFlag(val registryName: String) {
    HISTORY("FEATURE_READ_HEALTH_DATA_HISTORY"),
    SKIN_TEMPERATURE("FEATURE_SKIN_TEMPERATURE"),
    PLANNED_EXERCISE("FEATURE_PLANNED_EXERCISE"),
    MINDFULNESS("FEATURE_MINDFULNESS_SESSION")
}

private const val P = "android.permission.health."

enum class HealthDataType(
    val id: String,
    val category: HealthCategory,
    val kind: HealthKind,
    val aggregation: HealthAggregation,
    val unit: String,
    val dayAttribution: HealthDayAttribution = HealthDayAttribution.START,
    /** Simple class name of the Health Connect record, null for iOS-only types. */
    val hcRecord: String? = null,
    val hcPermission: String? = null,
    val hcFeatureFlag: HealthFeatureFlag? = null,
    val androidTier: HealthAndroidTier? = null,
    val exported: Boolean = true,
    /** Registry status "reserved": declared for parity but not readable with the pinned SDKs. */
    val reserved: Boolean = false,
    val categoryCodes: Map<Int, String> = emptyMap(),
    val hkIdentifiers: List<String> = emptyList()
) {
    // -- activity ----------------------------------------------------
    STEPS("steps", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "count",
        hcRecord = "StepsRecord",
        hcPermission = P + "READ_STEPS",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierStepCount")),
    DISTANCE("distance", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hcRecord = "DistanceRecord",
        hcPermission = P + "READ_DISTANCE",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistanceWalkingRunning")),
    DISTANCE_CYCLING("distance_cycling", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistanceCycling")),
    DISTANCE_SWIMMING("distance_swimming", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistanceSwimming")),
    DISTANCE_DOWNHILL_SNOW_SPORTS("distance_downhill_snow_sports", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistanceDownhillSnowSports")),
    DISTANCE_ROWING("distance_rowing", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistanceRowing")),
    DISTANCE_PADDLE_SPORTS("distance_paddle_sports", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistancePaddleSports")),
    DISTANCE_CROSS_COUNTRY_SKIING("distance_cross_country_skiing", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistanceCrossCountrySkiing")),
    DISTANCE_SKATING_SPORTS("distance_skating_sports", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistanceSkatingSports")),
    SWIMMING_STROKE_COUNT("swimming_stroke_count", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierSwimmingStrokeCount")),
    WHEELCHAIR_PUSHES("wheelchair_pushes", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "count",
        hcRecord = "WheelchairPushesRecord",
        hcPermission = P + "READ_WHEELCHAIR_PUSHES",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierPushCount")),
    DISTANCE_WHEELCHAIR("distance_wheelchair", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDistanceWheelchair")),
    FLOORS_CLIMBED("floors_climbed", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "count",
        hcRecord = "FloorsClimbedRecord",
        hcPermission = P + "READ_FLOORS_CLIMBED",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierFlightsClimbed")),
    ELEVATION_GAINED("elevation_gained", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "m",
        hcRecord = "ElevationGainedRecord",
        hcPermission = P + "READ_ELEVATION_GAINED",
        androidTier = HealthAndroidTier.EXTENDED),
    ACTIVE_ENERGY("active_energy", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "kcal",
        hcRecord = "ActiveCaloriesBurnedRecord",
        hcPermission = P + "READ_ACTIVE_CALORIES_BURNED",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierActiveEnergyBurned")),
    TOTAL_ENERGY("total_energy", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "kcal",
        hcRecord = "TotalCaloriesBurnedRecord",
        hcPermission = P + "READ_TOTAL_CALORIES_BURNED",
        androidTier = HealthAndroidTier.CORE),
    RESTING_ENERGY("resting_energy", HealthCategory.ACTIVITY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "kcal",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierBasalEnergyBurned")),
    EXERCISE_MINUTES("exercise_minutes", HealthCategory.ACTIVITY, HealthKind.DURATION, HealthAggregation.DURATION, "s",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierAppleExerciseTime")),
    STAND_MINUTES("stand_minutes", HealthCategory.ACTIVITY, HealthKind.DURATION, HealthAggregation.DURATION, "s",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierAppleStandTime")),
    MOVE_MINUTES("move_minutes", HealthCategory.ACTIVITY, HealthKind.DURATION, HealthAggregation.DURATION, "s",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierAppleMoveTime")),
    STAND_HOURS("stand_hours", HealthCategory.ACTIVITY, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "stood", 1 to "idle"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierAppleStandHour")),
    LOW_CARDIO_FITNESS_EVENT("low_cardio_fitness_event", HealthCategory.ACTIVITY, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(1 to "low_fitness"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierLowCardioFitnessEvent")),
    WORKOUT("workout", HealthCategory.ACTIVITY, HealthKind.SESSION, HealthAggregation.DURATION, "s",
        hcRecord = "ExerciseSessionRecord",
        hcPermission = P + "READ_EXERCISE",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKWorkoutTypeIdentifier")),
    PLANNED_WORKOUT("planned_workout", HealthCategory.ACTIVITY, HealthKind.SESSION, HealthAggregation.COUNT, "s",
        hcRecord = "PlannedExerciseSessionRecord",
        hcPermission = P + "READ_PLANNED_EXERCISE",
        hcFeatureFlag = HealthFeatureFlag.PLANNED_EXERCISE,
        androidTier = HealthAndroidTier.EXTENDED),
    ACTIVITY_INTENSITY("activity_intensity", HealthCategory.ACTIVITY, HealthKind.DURATION, HealthAggregation.DURATION, "s",
        hcRecord = "ActivityIntensityRecord",
        hcPermission = P + "READ_ACTIVITY_INTENSITY",
        androidTier = HealthAndroidTier.EXTENDED,
        reserved = true,
        categoryCodes = mapOf(0 to "moderate", 1 to "vigorous")),
    SPEED("speed", HealthCategory.ACTIVITY, HealthKind.SERIES, HealthAggregation.AVERAGE, "m/s",
        hcRecord = "SpeedRecord",
        hcPermission = P + "READ_SPEED",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierRunningSpeed", "HKQuantityTypeIdentifierCyclingSpeed")),
    POWER("power", HealthCategory.ACTIVITY, HealthKind.SERIES, HealthAggregation.AVERAGE, "W",
        hcRecord = "PowerRecord",
        hcPermission = P + "READ_POWER",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierCyclingPower", "HKQuantityTypeIdentifierRunningPower")),
    CYCLING_CADENCE("cycling_cadence", HealthCategory.ACTIVITY, HealthKind.SERIES, HealthAggregation.AVERAGE, "count/min",
        hcRecord = "CyclingPedalingCadenceRecord",
        hcPermission = P + "READ_EXERCISE",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierCyclingCadence")),
    STEP_CADENCE("step_cadence", HealthCategory.ACTIVITY, HealthKind.SERIES, HealthAggregation.AVERAGE, "count/min",
        hcRecord = "StepsCadenceRecord",
        hcPermission = P + "READ_STEPS",
        androidTier = HealthAndroidTier.CORE),
    RUNNING_STRIDE_LENGTH("running_stride_length", HealthCategory.ACTIVITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierRunningStrideLength")),
    RUNNING_GROUND_CONTACT_TIME("running_ground_contact_time", HealthCategory.ACTIVITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "ms",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierRunningGroundContactTime")),
    RUNNING_VERTICAL_OSCILLATION("running_vertical_oscillation", HealthCategory.ACTIVITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierRunningVerticalOscillation")),
    CYCLING_FTP("cycling_ftp", HealthCategory.ACTIVITY, HealthKind.DISCRETE, HealthAggregation.LATEST, "W",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierCyclingFunctionalThresholdPower")),
    PHYSICAL_EFFORT("physical_effort", HealthCategory.ACTIVITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "kcal/hr·kg",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierPhysicalEffort")),
    WORKOUT_EFFORT_SCORE("workout_effort_score", HealthCategory.ACTIVITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierWorkoutEffortScore")),
    ESTIMATED_WORKOUT_EFFORT_SCORE("estimated_workout_effort_score", HealthCategory.ACTIVITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierEstimatedWorkoutEffortScore")),

    // -- body --------------------------------------------------------
    WEIGHT("weight", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "kg",
        hcRecord = "WeightRecord",
        hcPermission = P + "READ_WEIGHT",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierBodyMass")),
    HEIGHT("height", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "m",
        hcRecord = "HeightRecord",
        hcPermission = P + "READ_HEIGHT",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierHeight")),
    BODY_FAT("body_fat", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "%",
        hcRecord = "BodyFatRecord",
        hcPermission = P + "READ_BODY_FAT",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierBodyFatPercentage")),
    LEAN_BODY_MASS("lean_body_mass", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "kg",
        hcRecord = "LeanBodyMassRecord",
        hcPermission = P + "READ_LEAN_BODY_MASS",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierLeanBodyMass")),
    BONE_MASS("bone_mass", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "kg",
        hcRecord = "BoneMassRecord",
        hcPermission = P + "READ_BONE_MASS",
        androidTier = HealthAndroidTier.EXTENDED),
    BODY_WATER_MASS("body_water_mass", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "kg",
        hcRecord = "BodyWaterMassRecord",
        hcPermission = P + "READ_BODY_WATER_MASS",
        androidTier = HealthAndroidTier.EXTENDED),
    BASAL_METABOLIC_RATE("basal_metabolic_rate", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "kcal/d",
        hcRecord = "BasalMetabolicRateRecord",
        hcPermission = P + "READ_BASAL_METABOLIC_RATE",
        androidTier = HealthAndroidTier.EXTENDED),
    BMI("bmi", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierBodyMassIndex")),
    WAIST_CIRCUMFERENCE("waist_circumference", HealthCategory.BODY, HealthKind.DISCRETE, HealthAggregation.LATEST, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierWaistCircumference")),

    // -- cycle_tracking ----------------------------------------------
    MENSTRUAL_FLOW("menstrual_flow", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        hcRecord = "MenstruationFlowRecord",
        hcPermission = P + "READ_MENSTRUATION",
        androidTier = HealthAndroidTier.EXTENDED,
        categoryCodes = mapOf(1 to "unspecified", 2 to "light", 3 to "medium", 4 to "heavy", 5 to "none"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierMenstrualFlow")),
    MENSTRUATION_PERIOD("menstruation_period", HealthCategory.CYCLE_TRACKING, HealthKind.DURATION, HealthAggregation.DURATION, "days",
        dayAttribution = HealthDayAttribution.SPAN,
        hcRecord = "MenstruationPeriodRecord",
        hcPermission = P + "READ_MENSTRUATION",
        androidTier = HealthAndroidTier.EXTENDED),
    INTERMENSTRUAL_BLEEDING("intermenstrual_bleeding", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        hcRecord = "IntermenstrualBleedingRecord",
        hcPermission = P + "READ_INTERMENSTRUAL_BLEEDING",
        androidTier = HealthAndroidTier.EXTENDED,
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierIntermenstrualBleeding")),
    OVULATION_TEST("ovulation_test", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        hcRecord = "OvulationTestRecord",
        hcPermission = P + "READ_OVULATION_TEST",
        androidTier = HealthAndroidTier.EXTENDED,
        categoryCodes = mapOf(1 to "negative", 2 to "positive", 3 to "indeterminate", 4 to "estrogen_surge"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierOvulationTestResult")),
    CERVICAL_MUCUS("cervical_mucus", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        hcRecord = "CervicalMucusRecord",
        hcPermission = P + "READ_CERVICAL_MUCUS",
        androidTier = HealthAndroidTier.EXTENDED,
        categoryCodes = mapOf(0 to "unknown", 1 to "dry", 2 to "sticky", 3 to "creamy", 4 to "watery", 5 to "egg_white", 6 to "unusual"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierCervicalMucusQuality")),
    SEXUAL_ACTIVITY("sexual_activity", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        hcRecord = "SexualActivityRecord",
        hcPermission = P + "READ_SEXUAL_ACTIVITY",
        androidTier = HealthAndroidTier.EXTENDED,
        categoryCodes = mapOf(0 to "unknown", 1 to "protected", 2 to "unprotected"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierSexualActivity")),
    BASAL_BODY_TEMPERATURE("basal_body_temperature", HealthCategory.CYCLE_TRACKING, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "degC",
        hcRecord = "BasalBodyTemperatureRecord",
        hcPermission = P + "READ_BASAL_BODY_TEMPERATURE",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierBasalBodyTemperature")),
    CONTRACEPTIVE("contraceptive", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        dayAttribution = HealthDayAttribution.SPAN,
        categoryCodes = mapOf(1 to "unspecified", 2 to "implant", 3 to "injection", 4 to "intrauterine_device", 5 to "intravaginal_ring", 6 to "oral", 7 to "patch"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierContraceptive")),
    PREGNANCY("pregnancy", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        dayAttribution = HealthDayAttribution.SPAN,
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierPregnancy")),
    PREGNANCY_TEST_RESULT("pregnancy_test_result", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(1 to "negative", 2 to "positive", 3 to "indeterminate"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierPregnancyTestResult")),
    PROGESTERONE_TEST_RESULT("progesterone_test_result", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(1 to "negative", 2 to "positive", 3 to "indeterminate"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierProgesteroneTestResult")),
    LACTATION("lactation", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        dayAttribution = HealthDayAttribution.SPAN,
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierLactation")),
    MENOPAUSAL_STATE("menopausal_state", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        dayAttribution = HealthDayAttribution.SPAN),
    BLEEDING_AFTER_MENOPAUSE("bleeding_after_menopause", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "occurred")),
    INFREQUENT_MENSTRUAL_CYCLES("infrequent_menstrual_cycles", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        dayAttribution = HealthDayAttribution.SPAN,
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierInfrequentMenstrualCycles")),
    IRREGULAR_MENSTRUAL_CYCLES("irregular_menstrual_cycles", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        dayAttribution = HealthDayAttribution.SPAN,
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierIrregularMenstrualCycles")),
    PERSISTENT_INTERMENSTRUAL_BLEEDING("persistent_intermenstrual_bleeding", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        dayAttribution = HealthDayAttribution.SPAN,
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierPersistentIntermenstrualBleeding")),
    PROLONGED_MENSTRUAL_PERIODS("prolonged_menstrual_periods", HealthCategory.CYCLE_TRACKING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        dayAttribution = HealthDayAttribution.SPAN,
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierProlongedMenstrualPeriods")),

    // -- hearing -----------------------------------------------------
    ENVIRONMENTAL_AUDIO_EXPOSURE("environmental_audio_exposure", HealthCategory.HEARING, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "dBASPL",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierEnvironmentalAudioExposure")),
    HEADPHONE_AUDIO_EXPOSURE("headphone_audio_exposure", HealthCategory.HEARING, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "dBASPL",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierHeadphoneAudioExposure")),
    ENVIRONMENTAL_SOUND_REDUCTION("environmental_sound_reduction", HealthCategory.HEARING, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "dBASPL",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierEnvironmentalSoundReduction")),
    ENVIRONMENTAL_AUDIO_EXPOSURE_EVENT("environmental_audio_exposure_event", HealthCategory.HEARING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(1 to "momentary_limit"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent")),
    HEADPHONE_AUDIO_EXPOSURE_EVENT("headphone_audio_exposure_event", HealthCategory.HEARING, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(1 to "seven_day_limit"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierHeadphoneAudioExposureEvent")),

    // -- heart -------------------------------------------------------
    HEART_RATE("heart_rate", HealthCategory.HEART, HealthKind.SERIES, HealthAggregation.MIN_MAX, "count/min",
        hcRecord = "HeartRateRecord",
        hcPermission = P + "READ_HEART_RATE",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierHeartRate")),
    RESTING_HEART_RATE("resting_heart_rate", HealthCategory.HEART, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "count/min",
        hcRecord = "RestingHeartRateRecord",
        hcPermission = P + "READ_RESTING_HEART_RATE",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierRestingHeartRate")),
    HRV_RMSSD("hrv_rmssd", HealthCategory.HEART, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "ms",
        hcRecord = "HeartRateVariabilityRmssdRecord",
        hcPermission = P + "READ_HEART_RATE_VARIABILITY",
        androidTier = HealthAndroidTier.CORE,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierHeartRateVariabilityRMSSD")),
    HRV_SDNN("hrv_sdnn", HealthCategory.HEART, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "ms",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierHeartRateVariabilitySDNN")),
    BLOOD_PRESSURE("blood_pressure", HealthCategory.HEART, HealthKind.DISCRETE, HealthAggregation.MIN_MAX, "mmHg",
        hcRecord = "BloodPressureRecord",
        hcPermission = P + "READ_BLOOD_PRESSURE",
        androidTier = HealthAndroidTier.EXTENDED,
        categoryCodes = mapOf(0 to "unknown", 1 to "standing_up", 2 to "sitting_down", 3 to "lying_down", 4 to "reclining"),
        hkIdentifiers = listOf("HKCorrelationTypeIdentifierBloodPressure")),
    VO2_MAX("vo2_max", HealthCategory.HEART, HealthKind.DISCRETE, HealthAggregation.LATEST, "mL/min·kg",
        hcRecord = "Vo2MaxRecord",
        hcPermission = P + "READ_VO2_MAX",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierVO2Max")),
    WALKING_HEART_RATE_AVERAGE("walking_heart_rate_average", HealthCategory.HEART, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "count/min",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierWalkingHeartRateAverage")),
    HEART_RATE_RECOVERY_ONE_MINUTE("heart_rate_recovery_one_minute", HealthCategory.HEART, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "count/min",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierHeartRateRecoveryOneMinute")),
    AFIB_BURDEN("afib_burden", HealthCategory.HEART, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "%",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierAtrialFibrillationBurden")),
    HIGH_HEART_RATE_EVENT("high_heart_rate_event", HealthCategory.HEART, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierHighHeartRateEvent")),
    LOW_HEART_RATE_EVENT("low_heart_rate_event", HealthCategory.HEART, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierLowHeartRateEvent")),
    IRREGULAR_HEART_RHYTHM_EVENT("irregular_heart_rhythm_event", HealthCategory.HEART, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierIrregularHeartRhythmEvent")),
    HYPERTENSION_EVENT("hypertension_event", HealthCategory.HEART, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "occurred")),

    // -- mental_wellbeing --------------------------------------------
    MINDFULNESS_SESSION("mindfulness_session", HealthCategory.MENTAL_WELLBEING, HealthKind.DURATION, HealthAggregation.DURATION, "s",
        hcRecord = "MindfulnessSessionRecord",
        hcPermission = P + "READ_MINDFULNESS",
        hcFeatureFlag = HealthFeatureFlag.MINDFULNESS,
        androidTier = HealthAndroidTier.EXTENDED,
        categoryCodes = mapOf(0 to "unknown", 1 to "meditation", 2 to "other", 3 to "breathing", 4 to "music", 5 to "movement", 6 to "unguided"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierMindfulSession")),
    STATE_OF_MIND("state_of_mind", HealthCategory.MENTAL_WELLBEING, HealthKind.CATEGORY, HealthAggregation.COUNT, "none",
        categoryCodes = mapOf(1 to "momentary_emotion", 2 to "daily_mood"),
        hkIdentifiers = listOf("HKStateOfMindTypeIdentifier")),
    ASSESSMENT_GAD7("assessment_gad7", HealthCategory.MENTAL_WELLBEING, HealthKind.DISCRETE, HealthAggregation.LATEST, "count",
        categoryCodes = mapOf(0 to "none_to_minimal", 1 to "mild", 2 to "moderate", 3 to "severe"),
        hkIdentifiers = listOf("HKScoredAssessmentTypeIdentifierGAD7")),
    ASSESSMENT_PHQ9("assessment_phq9", HealthCategory.MENTAL_WELLBEING, HealthKind.DISCRETE, HealthAggregation.LATEST, "count",
        categoryCodes = mapOf(0 to "none_to_minimal", 1 to "mild", 2 to "moderate", 3 to "moderately_severe", 4 to "severe"),
        hkIdentifiers = listOf("HKScoredAssessmentTypeIdentifierPHQ9")),

    // -- mobility ----------------------------------------------------
    WALKING_SPEED("walking_speed", HealthCategory.MOBILITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "m/s",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierWalkingSpeed")),
    WALKING_STEP_LENGTH("walking_step_length", HealthCategory.MOBILITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierWalkingStepLength")),
    WALKING_ASYMMETRY("walking_asymmetry", HealthCategory.MOBILITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "%",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierWalkingAsymmetryPercentage")),
    WALKING_DOUBLE_SUPPORT("walking_double_support", HealthCategory.MOBILITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "%",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierWalkingDoubleSupportPercentage")),
    SIX_MINUTE_WALK_DISTANCE("six_minute_walk_distance", HealthCategory.MOBILITY, HealthKind.DISCRETE, HealthAggregation.LATEST, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierSixMinuteWalkTestDistance")),
    STAIR_ASCENT_SPEED("stair_ascent_speed", HealthCategory.MOBILITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "m/s",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierStairAscentSpeed")),
    STAIR_DESCENT_SPEED("stair_descent_speed", HealthCategory.MOBILITY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "m/s",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierStairDescentSpeed")),
    WALKING_STEADINESS("walking_steadiness", HealthCategory.MOBILITY, HealthKind.DISCRETE, HealthAggregation.LATEST, "%",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierAppleWalkingSteadiness")),
    WALKING_STEADINESS_EVENT("walking_steadiness_event", HealthCategory.MOBILITY, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(1 to "initial_low", 2 to "initial_very_low", 3 to "repeat_low", 4 to "repeat_very_low"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierAppleWalkingSteadinessEvent")),

    // -- nutrition ---------------------------------------------------
    HYDRATION("hydration", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mL",
        hcRecord = "HydrationRecord",
        hcPermission = P + "READ_HYDRATION",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryWater")),
    NUTRITION_RECORD("nutrition", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "kcal",
        hcRecord = "NutritionRecord",
        hcPermission = P + "READ_NUTRITION",
        androidTier = HealthAndroidTier.EXTENDED,
        exported = false,
        categoryCodes = mapOf(0 to "unknown", 1 to "breakfast", 2 to "lunch", 3 to "dinner", 4 to "snack")),
    DIETARY_ENERGY("dietary_energy", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "kcal",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryEnergyConsumed")),
    DIETARY_PROTEIN("dietary_protein", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "g",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryProtein")),
    DIETARY_CARBOHYDRATES("dietary_carbohydrates", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "g",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryCarbohydrates")),
    DIETARY_FAT_TOTAL("dietary_fat_total", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "g",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryFatTotal")),
    DIETARY_FAT_SATURATED("dietary_fat_saturated", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "g",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryFatSaturated")),
    DIETARY_FAT_MONOUNSATURATED("dietary_fat_monounsaturated", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "g",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryFatMonounsaturated")),
    DIETARY_FAT_POLYUNSATURATED("dietary_fat_polyunsaturated", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "g",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryFatPolyunsaturated")),
    DIETARY_CHOLESTEROL("dietary_cholesterol", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryCholesterol")),
    DIETARY_FIBER("dietary_fiber", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "g",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryFiber")),
    DIETARY_SUGAR("dietary_sugar", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "g",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietarySugar")),
    DIETARY_SODIUM("dietary_sodium", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietarySodium")),
    DIETARY_POTASSIUM("dietary_potassium", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryPotassium")),
    DIETARY_CALCIUM("dietary_calcium", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryCalcium")),
    DIETARY_IRON("dietary_iron", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryIron")),
    DIETARY_MAGNESIUM("dietary_magnesium", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryMagnesium")),
    DIETARY_ZINC("dietary_zinc", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryZinc")),
    DIETARY_PHOSPHORUS("dietary_phosphorus", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryPhosphorus")),
    DIETARY_CHLORIDE("dietary_chloride", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryChloride")),
    DIETARY_COPPER("dietary_copper", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryCopper")),
    DIETARY_MANGANESE("dietary_manganese", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryManganese")),
    DIETARY_SELENIUM("dietary_selenium", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietarySelenium")),
    DIETARY_CHROMIUM("dietary_chromium", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryChromium")),
    DIETARY_MOLYBDENUM("dietary_molybdenum", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryMolybdenum")),
    DIETARY_IODINE("dietary_iodine", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryIodine")),
    DIETARY_CAFFEINE("dietary_caffeine", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryCaffeine")),
    DIETARY_VITAMIN_A("dietary_vitamin_a", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryVitaminA")),
    DIETARY_VITAMIN_B6("dietary_vitamin_b6", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryVitaminB6")),
    DIETARY_VITAMIN_B12("dietary_vitamin_b12", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryVitaminB12")),
    DIETARY_VITAMIN_C("dietary_vitamin_c", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryVitaminC")),
    DIETARY_VITAMIN_D("dietary_vitamin_d", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryVitaminD")),
    DIETARY_VITAMIN_E("dietary_vitamin_e", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryVitaminE")),
    DIETARY_VITAMIN_K("dietary_vitamin_k", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryVitaminK")),
    DIETARY_THIAMIN("dietary_thiamin", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryThiamin")),
    DIETARY_RIBOFLAVIN("dietary_riboflavin", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryRiboflavin")),
    DIETARY_NIACIN("dietary_niacin", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryNiacin")),
    DIETARY_FOLATE("dietary_folate", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryFolate")),
    DIETARY_BIOTIN("dietary_biotin", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mcg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryBiotin")),
    DIETARY_PANTOTHENIC_ACID("dietary_pantothenic_acid", HealthCategory.NUTRITION, HealthKind.CUMULATIVE, HealthAggregation.SUM, "mg",
        exported = false,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierDietaryPantothenicAcid")),

    // -- respiratory -------------------------------------------------
    RESPIRATORY_RATE("respiratory_rate", HealthCategory.RESPIRATORY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "count/min",
        hcRecord = "RespiratoryRateRecord",
        hcPermission = P + "READ_RESPIRATORY_RATE",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierRespiratoryRate")),
    BLOOD_OXYGEN("blood_oxygen", HealthCategory.RESPIRATORY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "%",
        hcRecord = "OxygenSaturationRecord",
        hcPermission = P + "READ_OXYGEN_SATURATION",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierOxygenSaturation")),
    FEV1("fev1", HealthCategory.RESPIRATORY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "L",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierForcedExpiratoryVolume1")),
    FVC("fvc", HealthCategory.RESPIRATORY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "L",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierForcedVitalCapacity")),
    PEAK_EXPIRATORY_FLOW_RATE("peak_expiratory_flow_rate", HealthCategory.RESPIRATORY, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "L/min",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierPeakExpiratoryFlowRate")),
    INHALER_USAGE("inhaler_usage", HealthCategory.RESPIRATORY, HealthKind.CUMULATIVE, HealthAggregation.SUM, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierInhalerUsage")),

    // -- sleep -------------------------------------------------------
    SLEEP("sleep", HealthCategory.SLEEP, HealthKind.SESSION, HealthAggregation.DURATION, "s",
        dayAttribution = HealthDayAttribution.END,
        hcRecord = "SleepSessionRecord",
        hcPermission = P + "READ_SLEEP",
        androidTier = HealthAndroidTier.CORE,
        categoryCodes = mapOf(0 to "in_bed", 1 to "asleep_unspecified", 2 to "awake", 3 to "light", 4 to "deep", 5 to "rem", 6 to "out_of_bed"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierSleepAnalysis")),
    SLEEPING_WRIST_TEMPERATURE("sleeping_wrist_temperature", HealthCategory.SLEEP, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "degC",
        dayAttribution = HealthDayAttribution.END,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierAppleSleepingWristTemperature")),
    SLEEPING_BREATHING_DISTURBANCES("sleeping_breathing_disturbances", HealthCategory.SLEEP, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "count",
        dayAttribution = HealthDayAttribution.END,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances")),

    // -- symptoms ----------------------------------------------------
    SYMPTOM_ABDOMINAL_CRAMPS("symptom_abdominal_cramps", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierAbdominalCramps")),
    SYMPTOM_ACNE("symptom_acne", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierAcne")),
    SYMPTOM_APPETITE_CHANGES("symptom_appetite_changes", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "no_change", 2 to "decreased", 3 to "increased"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierAppetiteChanges")),
    SYMPTOM_BLADDER_INCONTINENCE("symptom_bladder_incontinence", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierBladderIncontinence")),
    SYMPTOM_BLOATING("symptom_bloating", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierBloating")),
    SYMPTOM_BREAST_PAIN("symptom_breast_pain", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierBreastPain")),
    SYMPTOM_CHEST_TIGHTNESS_OR_PAIN("symptom_chest_tightness_or_pain", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierChestTightnessOrPain")),
    SYMPTOM_CHILLS("symptom_chills", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierChills")),
    SYMPTOM_CONSTIPATION("symptom_constipation", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierConstipation")),
    SYMPTOM_COUGHING("symptom_coughing", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierCoughing")),
    SYMPTOM_DIARRHEA("symptom_diarrhea", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierDiarrhea")),
    SYMPTOM_DIZZINESS("symptom_dizziness", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierDizziness")),
    SYMPTOM_DRY_SKIN("symptom_dry_skin", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierDrySkin")),
    SYMPTOM_FAINTING("symptom_fainting", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierFainting")),
    SYMPTOM_FATIGUE("symptom_fatigue", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierFatigue")),
    SYMPTOM_FEVER("symptom_fever", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierFever")),
    SYMPTOM_GENERALIZED_BODY_ACHE("symptom_generalized_body_ache", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierGeneralizedBodyAche")),
    SYMPTOM_HAIR_LOSS("symptom_hair_loss", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierHairLoss")),
    SYMPTOM_HEADACHE("symptom_headache", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierHeadache")),
    SYMPTOM_HEARTBURN("symptom_heartburn", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierHeartburn")),
    SYMPTOM_HOT_FLASHES("symptom_hot_flashes", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierHotFlashes")),
    SYMPTOM_LOSS_OF_SMELL("symptom_loss_of_smell", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierLossOfSmell")),
    SYMPTOM_LOSS_OF_TASTE("symptom_loss_of_taste", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierLossOfTaste")),
    SYMPTOM_LOWER_BACK_PAIN("symptom_lower_back_pain", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierLowerBackPain")),
    SYMPTOM_MEMORY_LAPSE("symptom_memory_lapse", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierMemoryLapse")),
    SYMPTOM_MOOD_CHANGES("symptom_mood_changes", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "present", 1 to "not_present"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierMoodChanges")),
    SYMPTOM_NAUSEA("symptom_nausea", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierNausea")),
    SYMPTOM_NIGHT_SWEATS("symptom_night_sweats", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierNightSweats")),
    SYMPTOM_PELVIC_PAIN("symptom_pelvic_pain", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierPelvicPain")),
    SYMPTOM_RAPID_POUNDING_OR_FLUTTERING_HEARTBEAT("symptom_rapid_pounding_or_fluttering_heartbeat", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat")),
    SYMPTOM_RUNNY_NOSE("symptom_runny_nose", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierRunnyNose")),
    SYMPTOM_SHORTNESS_OF_BREATH("symptom_shortness_of_breath", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierShortnessOfBreath")),
    SYMPTOM_SINUS_CONGESTION("symptom_sinus_congestion", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierSinusCongestion")),
    SYMPTOM_SKIPPED_HEARTBEAT("symptom_skipped_heartbeat", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierSkippedHeartbeat")),
    SYMPTOM_SLEEP_CHANGES("symptom_sleep_changes", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "present", 1 to "not_present"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierSleepChanges")),
    SYMPTOM_SORE_THROAT("symptom_sore_throat", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierSoreThroat")),
    SYMPTOM_VAGINAL_DRYNESS("symptom_vaginal_dryness", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierVaginalDryness")),
    SYMPTOM_VOMITING("symptom_vomiting", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierVomiting")),
    SYMPTOM_WHEEZING("symptom_wheezing", HealthCategory.SYMPTOMS, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "unspecified", 1 to "not_present", 2 to "mild", 3 to "moderate", 4 to "severe"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierWheezing")),

    // -- vitals ------------------------------------------------------
    BLOOD_GLUCOSE("blood_glucose", HealthCategory.VITALS, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "mmol/L",
        hcRecord = "BloodGlucoseRecord",
        hcPermission = P + "READ_BLOOD_GLUCOSE",
        androidTier = HealthAndroidTier.EXTENDED,
        categoryCodes = mapOf(0 to "unknown", 1 to "interstitial_fluid", 2 to "capillary_blood", 3 to "plasma", 4 to "serum", 5 to "tears", 6 to "whole_blood"),
        hkIdentifiers = listOf("HKQuantityTypeIdentifierBloodGlucose")),
    BODY_TEMPERATURE("body_temperature", HealthCategory.VITALS, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "degC",
        hcRecord = "BodyTemperatureRecord",
        hcPermission = P + "READ_BODY_TEMPERATURE",
        androidTier = HealthAndroidTier.EXTENDED,
        hkIdentifiers = listOf("HKQuantityTypeIdentifierBodyTemperature")),
    SKIN_TEMPERATURE("skin_temperature", HealthCategory.VITALS, HealthKind.SERIES, HealthAggregation.AVERAGE, "degC",
        hcRecord = "SkinTemperatureRecord",
        hcPermission = P + "READ_SKIN_TEMPERATURE",
        hcFeatureFlag = HealthFeatureFlag.SKIN_TEMPERATURE,
        androidTier = HealthAndroidTier.EXTENDED),
    ELECTRODERMAL_ACTIVITY("electrodermal_activity", HealthCategory.VITALS, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "mcS",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierElectrodermalActivity")),
    PERIPHERAL_PERFUSION_INDEX("peripheral_perfusion_index", HealthCategory.VITALS, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "%",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierPeripheralPerfusionIndex")),
    INSULIN_DELIVERY("insulin_delivery", HealthCategory.VITALS, HealthKind.CUMULATIVE, HealthAggregation.SUM, "IU",
        categoryCodes = mapOf(1 to "basal", 2 to "bolus"),
        hkIdentifiers = listOf("HKQuantityTypeIdentifierInsulinDelivery")),

    // -- other -------------------------------------------------------
    UV_EXPOSURE("uv_exposure", HealthCategory.OTHER, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierUVExposure")),
    TIME_IN_DAYLIGHT("time_in_daylight", HealthCategory.OTHER, HealthKind.DURATION, HealthAggregation.DURATION, "s",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierTimeInDaylight")),
    NUMBER_OF_TIMES_FALLEN("number_of_times_fallen", HealthCategory.OTHER, HealthKind.CUMULATIVE, HealthAggregation.SUM, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierNumberOfTimesFallen")),
    ALCOHOLIC_BEVERAGES("alcoholic_beverages", HealthCategory.OTHER, HealthKind.CUMULATIVE, HealthAggregation.SUM, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierNumberOfAlcoholicBeverages")),
    BLOOD_ALCOHOL_CONTENT("blood_alcohol_content", HealthCategory.OTHER, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "%",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierBloodAlcoholContent")),
    TOOTHBRUSHING_EVENT("toothbrushing_event", HealthCategory.OTHER, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierToothbrushingEvent")),
    HANDWASHING_EVENT("handwashing_event", HealthCategory.OTHER, HealthKind.CATEGORY, HealthAggregation.COUNT, "count",
        categoryCodes = mapOf(0 to "occurred"),
        hkIdentifiers = listOf("HKCategoryTypeIdentifierHandwashingEvent")),
    UNDERWATER_DEPTH("underwater_depth", HealthCategory.OTHER, HealthKind.DISCRETE, HealthAggregation.MIN_MAX, "m",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierUnderwaterDepth")),
    WATER_TEMPERATURE("water_temperature", HealthCategory.OTHER, HealthKind.DISCRETE, HealthAggregation.AVERAGE, "degC",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierWaterTemperature")),
    NIKE_FUEL("nike_fuel", HealthCategory.OTHER, HealthKind.CUMULATIVE, HealthAggregation.SUM, "count",
        hkIdentifiers = listOf("HKQuantityTypeIdentifierNikeFuel")),
    ACTIVITY_SUMMARY("activity_summary", HealthCategory.OTHER, HealthKind.DISCRETE, HealthAggregation.LATEST, "kcal",
        reserved = true,
        hkIdentifiers = listOf("HKActivitySummaryTypeIdentifier")),
    ELECTROCARDIOGRAM("electrocardiogram", HealthCategory.OTHER, HealthKind.DISCRETE, HealthAggregation.COUNT, "count/min",
        reserved = true,
        categoryCodes = mapOf(0 to "not_set", 1 to "sinus_rhythm", 2 to "atrial_fibrillation", 3 to "inconclusive_low_heart_rate", 4 to "inconclusive_high_heart_rate", 5 to "inconclusive_poor_reading", 6 to "inconclusive_other", 100 to "unrecognized"),
        hkIdentifiers = listOf("HKDataTypeIdentifierElectrocardiogram")),
    HEARTBEAT_SERIES("heartbeat_series", HealthCategory.OTHER, HealthKind.DISCRETE, HealthAggregation.COUNT, "count",
        reserved = true,
        hkIdentifiers = listOf("HKDataTypeIdentifierHeartbeatSeries")),
    AUDIOGRAM("audiogram", HealthCategory.OTHER, HealthKind.DISCRETE, HealthAggregation.COUNT, "count",
        reserved = true,
        hkIdentifiers = listOf("HKDataTypeIdentifierAudiogram"));

    /** True when connect-client 1.1.0 can read this type on Android (reserved types are not). */
    val sdkAvailable: Boolean get() = hcRecord != null && hcPermission != null && !reserved

    val isSumType: Boolean get() = aggregation == HealthAggregation.SUM && kind == HealthKind.CUMULATIVE

    /** Day totals come from Health Connect's priority-deduplicated aggregate instead of local sums. */
    val usesPlatformAggregate: Boolean
        get() = sdkAvailable && this in PLATFORM_AGGREGATE_TYPES

    val isSeriesType: Boolean get() = kind == HealthKind.SERIES

    val isDurationLike: Boolean
        get() = aggregation == HealthAggregation.DURATION || kind == HealthKind.SESSION || kind == HealthKind.DURATION

    /** Virtual nutrition roll-ups derived from `nutrition.extra_json` on Android. */
    val isVirtualDietary: Boolean get() = id.startsWith("dietary_")

    /** Humanised fallback label when no string resource exists (e.g. imported raw ids). */
    fun displayFallback(): String = humanise(id)

    companion object {
        const val REGISTRY_VERSION = 1

        val canonicalUnits: Set<String> = setOf(
            "count", "m", "kcal", "kcal/d", "count/min", "ms", "%", "degC", "mmHg", "mmol/L", "kg", "s", "L",
            "mL", "g", "mg", "mcg", "m/s", "W", "dBASPL", "mL/min·kg", "kcal/hr·kg", "count/hr", "IU", "L/min",
            "mcS", "days", "none"
        )

        private val byIdMap: Map<String, HealthDataType> by lazy { entries.associateBy { it.id } }

        fun byId(id: String): HealthDataType? = byIdMap[id]

        val sdkTypes: List<HealthDataType> by lazy { entries.filter { it.sdkAvailable } }

        val coreTypes: List<HealthDataType> by lazy { sdkTypes.filter { it.androidTier == HealthAndroidTier.CORE } }

        val extendedTypes: List<HealthDataType> by lazy { sdkTypes.filter { it.androidTier == HealthAndroidTier.EXTENDED } }

        fun forCategory(category: HealthCategory): List<HealthDataType> = entries.filter { it.category == category }

        /** Types whose daily total Health Connect aggregates for us (priority-deduped across sources). */
        val PLATFORM_AGGREGATE_TYPES: Set<HealthDataType> by lazy {
            setOf(STEPS, DISTANCE, ACTIVE_ENERGY, TOTAL_ENERGY, FLOORS_CLIMBED, ELEVATION_GAINED, HYDRATION, WHEELCHAIR_PUSHES, WORKOUT)
        }

        /** `dietary_*` slug → key inside `nutrition.extra_json`. */
        val dietaryExtraKeys: Map<HealthDataType, String> by lazy {
            entries.filter { it.isVirtualDietary }.associateWith { it.id.removePrefix("dietary_") }
        }

        fun humanise(slug: String): String = slug
            .removePrefix("symptom_")
            .split('_')
            .filter { it.isNotBlank() }
            .joinToString(" ") { part -> part.replaceFirstChar { c -> c.uppercaseChar() } }
    }
}
