import Foundation

/// Loads the bundled exercise catalogue generated by `scripts/import_exercises_dataset.py`
/// from https://github.com/hasaneyldrm/exercises-dataset (text/metadata MIT; media © Gym visual).
nonisolated enum ExerciseCatalogLoader {
    static let mediaAttribution = "© Gym visual — https://gymvisual.com/"

    private static let lock = NSLock()
    private static var cachedItems: [ExerciseLibraryItem]?

    static func load() -> [ExerciseLibraryItem] {
        lock.lock()
        defer { lock.unlock() }
        if let cachedItems {
            return cachedItems
        }

        guard
            let url = exercisesJSONURL(),
            let data = try? Data(contentsOf: url),
            let items = try? items(from: data)
        else {
            cachedItems = []
            return []
        }

        cachedItems = items
        return items
    }

    static func exercisesJSONURL() -> URL? {
        Bundle.main.url(forResource: "exercises", withExtension: "json")
    }

    static func items(from data: Data) throws -> [ExerciseLibraryItem] {
        try JSONDecoder().decode([ExerciseCatalogRecord].self, from: data)
            .compactMap(libraryItem(from:))
            .sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
    }

    static func libraryItem(from record: ExerciseCatalogRecord) -> ExerciseLibraryItem? {
        let id = record.id.trimmingCharacters(in: .whitespacesAndNewlines)
        let name = record.name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !id.isEmpty, !name.isEmpty else {
            return nil
        }

        return ExerciseLibraryItem(
            id: id,
            name: ExerciseLibraryItem.metadataTitle(name),
            bodyPart: record.bodyPart,
            rawEquipment: record.equipment,
            primaryMuscles: [record.target],
            secondaryMuscles: record.secondaryMuscles,
            instructions: record.instructions,
            imageURL: record.imageUrl.flatMap(remoteURL),
            gifURL: record.gifUrl.flatMap(remoteURL)
        )
    }

    private static func remoteURL(_ string: String) -> URL? {
        guard let url = URL(string: string), url.scheme == "https" else { return nil }
        return url
    }
}

nonisolated struct ExerciseCatalogRecord: Decodable {
    let id: String
    let name: String
    let bodyPart: String
    let target: String
    let equipment: String
    let secondaryMuscles: [String]
    let instructions: [String]
    let gifUrl: String?
    let imageUrl: String?
}
